### ISSUE TITLE
Test failures with bouncycastle 1.70 on Fedora 36

### ISSUE THREAD

**Issue by ellert** [italiangrid/voms-api-java#28]
With the update to bouncycastle 1.70 in Fedora 36 (rawhide) the voms-api-java build started failing due to test failures.
I did not file an issue for this before, because it was potentially related to the failures in eu-emi/canl-java#115, However, that issue is now resolved, and the test failures in voma-api-java remain.

The tests that fail do so due to an exception:
java.lang.IllegalStateException: object explicit - implicit expected.

~~~
[INFO] Running org.italiangrid.voms.test.ac.TestACGeneration
[ERROR] Tests run: 6, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.26 s <<< FAILURE! - in org.italiangrid.voms.test.ac.TestACGeneration
[ERROR] org.italiangrid.voms.test.ac.TestACGeneration.testGeneratedACParsing  Time elapsed: 0.007 s  <<< ERROR!
java.lang.IllegalStateException: object explicit - implicit expected.
	at org.italiangrid.voms.test.ac.TestACGeneration.testGeneratedACParsing(TestACGeneration.java:201)
[ERROR] org.italiangrid.voms.test.ac.TestACGeneration.testACValidation  Time elapsed: 0.005 s  <<< ERROR!
java.lang.IllegalStateException: object explicit - implicit expected.
	at org.italiangrid.voms.test.ac.TestACGeneration.testACValidation(TestACGeneration.java:243)
[ERROR] org.italiangrid.voms.test.ac.TestACGeneration.testRevokedAACertValidationFailure  Time elapsed: 0.005 s  <<< ERROR!
java.lang.IllegalStateException: object explicit - implicit expected.
	at org.italiangrid.voms.test.ac.TestACGeneration.testRevokedAACertValidationFailure(TestACGeneration.java:299)
[ERROR] org.italiangrid.voms.test.ac.TestACGeneration.testExpiredAACertValidationFailure  Time elapsed: 0.006 s  <<< ERROR!
java.lang.IllegalStateException: object explicit - implicit expected.
	at org.italiangrid.voms.test.ac.TestACGeneration.testExpiredAACertValidationFailure(TestACGeneration.java:282)
[ERROR] org.italiangrid.voms.test.ac.TestACGeneration.testLSCValidationFailure  Time elapsed: 0.006 s  <<< ERROR!
java.lang.IllegalStateException: object explicit - implicit expected.
	at org.italiangrid.voms.test.ac.TestACGeneration.testLSCValidationFailure(TestACGeneration.java:262)
[INFO] Running org.italiangrid.voms.test.ac.TestFakeVOMSACService
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.014 s <<< FAILURE! - in org.italiangrid.voms.test.ac.TestFakeVOMSACService
[ERROR] org.italiangrid.voms.test.ac.TestFakeVOMSACService.testFakeAcServiceCreation  Time elapsed: 0.005 s  <<< ERROR!
java.lang.IllegalStateException: object explicit - implicit expected.
	at org.italiangrid.voms.test.ac.TestFakeVOMSACService.testFakeAcServiceCreation(TestFakeVOMSACService.java:74)
~~~

**Comment by ellert** [comment]
The exception (object explicit - implicit expected) is thrown by bouncycastle in the ASN1TaggedObject class:

https://github.com/bcgit/bc-java/blob/80f7059ae813f4f5a2cba1757bc19b3219219a18/core/src/main/java/org/bouncycastle/asn1/ASN1TaggedObject.java#L352
https://github.com/bcgit/bc-java/blob/80f7059ae813f4f5a2cba1757bc19b3219219a18/core/src/main/java/org/bouncycastle/asn1/ASN1TaggedObject.java#L394
https://github.com/bcgit/bc-java/blob/80f7059ae813f4f5a2cba1757bc19b3219219a18/core/src/main/java/org/bouncycastle/asn1/ASN1TaggedObject.java#L402

This class was updated for BC 1.70, these exceptions were not thrown before. How should voms-api-java be adapted to these changes in BC?
